connectionReferences:
  - connectionReferenceLogicalName: is_multieurlexsearchagent_q3PtOK.cr.shared_commondataser.b257464b-e284-4f1a-8c59-6c5466ea87d2
    connectorId: /providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps
